version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
    - location: scripts/BeforeInstall
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
    - location: scripts/ApplicationStop
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/AfterInstall
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/ApplicationStart
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/ValidateService
      timeout: 300
      runas: root